### PR TITLE
New convoy mission

### PR DESCRIPTION
**Pull request by ghost**
Hi,

I have created a convoy mission. It was quite time consuming to get it work smoothly.
I did a lot of testing. I hope it gets into the next release. :-)
## Mission description

3 Hunters (one with MG and one with grenade launcher) with 12 soldiers (inside the Hunters) start in the north of Stratis. They try to get to the south of the map. The players have to stop the convoy and kill all soldiers. They then get rewarded with an ammobox with some good weapons and as a bonus if they manage to not destroy the vehicles of the convoy, they additionally get the Hunters.

It's quite hard to solo this mission. A team of 3 to 5 players is recommted. I can imagine that the mission is even more fun when you have to fight the other player teams additionally.
## Some technical details
- The convoy mainly drive on the road. Only if they get attacked they may get off road for a short time (while they get attacked).
- The marker position of the mission gets updated every 10 seconds to the current location of the group leader of the convoy.
- Sometimes the cars get stucked on objects that spawned on the the road. But that is not so fatal.

### CODE REVIEW

**Comment by humangenome** [comment]
Very cool idea!

**Comment by antthor** [comment]
Would this work independent of the other pull requests you made?

**Comment by ghost** [comment]
Yes, it's independent from my other changes. The 404convoy branch only includes the changes for the convoy mission.

**Comment by antthor** [comment]
Cool, we will put it in.

**Comment by Krunch** [comment]
There is an issue with one of the files: mainMissionController.sqf

_MainMissions variable should be changed back to _MMarray

It somehow changed names with the commits.

**Comment by ghost** [comment]
Yeah. I fixed it already but forgot to push it :/ (was a merging mistake)

**Pull request merged**
